import type { Metadata } from 'next';
import { Lato, Montserrat } from 'next/font/google';
import './globals.css';

const lato = Lato({
	variable: '--font-lato',
	subsets: ['latin'],
	weight: ['400', '700'],
});

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body className={`${lato.variable} ${montserrat.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
